### ISSUE TITLE
Chrome 9: popup only shown once with wrong size

### ISSUE THREAD

**Issue by alopix** [gregghz/passgen#1]
This extension always worked fine until some days ago. Chrome 8 was not the problem, but Chrome 9 apparently it is.
The popup only shows the first time every new browser-session I click on the icon. But that's not the only problem. The popup is too small. i only see a small square, so there is no reload button and only about 1 character is visible in the password-field :(

Using Chrome 9.0.572.0 dev on a Mac.

**Comment by gregghz** [comment]
Thanks for reporting this. I've also confirmed it as an issue on 9.0.575.0 (65322) Ubuntu 10.10.

**Comment by gregghz** [comment]
I'm hoping to have a new release tonight that will address this issue.

**Comment by gregghz** [comment]
I've release 1.0. A fix for this issue is included. And just to note, 1.0 is mostly a backend change, little has changed that is user facing.

**Comment by alopix** [comment]
Works fine again :)
Thanks!

**Comment by tobyyates772-ship-it** [comment]
thanks
